// Code generated by oto; DO NOT EDIT.

// HeadersFunc allows you to mutate headers for each request.
// Useful for adding authorization into the client.
interface HeadersFunc {
	(headers: Headers): void;
}

// Client provides access to remote services.
export class Client {
	// basepath is the path prefix for the requests.
	// This may be a path, or an absolute URL.
	public basepath: String = '/api/oto/'
	// headers allows calling code to mutate the HTTP
	// headers of the underlying HTTP requests.
	public headers?: HeadersFunc
}


// GreeterService makes nice greetings.
export class GreeterService {
	constructor(readonly client: Client) {}
	
	// Greet makes a greeting.
	async greet(greetRequest?: GreetRequest, modifyHeaders?: HeadersFunc): Promise<GreetResponse> {
		if (greetRequest == null) {
			greetRequest = new GreetRequest();
		}
		const headers: Headers = new Headers();
		headers.set('Accept', 'application/json');
		headers.set('Content-Type', 'application/json');
		if (this.client.headers) {
			await this.client.headers(headers);
		}
		if (modifyHeaders) {
			await modifyHeaders(headers)
		}
		const response = await fetch(this.client.basepath + 'GreeterService.Greet', {
			method: 'POST',
			headers: headers,
			body: JSON.stringify(greetRequest),
		})
		if (response.status !== 200) {
			throw new Error(`GreeterService.Greet: ${response.status} ${response.statusText}`);
		}
		return response.json().then((json) => {
			if (json.error) {
				throw new Error(json.error);
			}
			return new GreetResponse(json);
		})
	}
	
}



// GreetRequest is the request object for GreeterService.Greet.
export class GreetRequest {
	constructor(data?: any) {
		if (data) {
		
			
			this.name = data.name;
			
		
		}
	}

	// Name is the person to greet.
	name: string = stringDefault;

}

// GreetResponse is the response object containing a person's greeting.
export class GreetResponse {
	constructor(data?: any) {
		if (data) {
		
			
			this.greeting = data.greeting;
			
		
			
			this.error = data.error;
			
		
		}
	}

	// Greeting is the greeting that was generated.
	greeting: string = stringDefault;

	// Error is string explaining what went wrong. Empty if everything was fine.
	error: string = stringDefault;

}


// these defaults make the template easier to write.
const stringDefault = ''
const numberDefault = 0
const booleanDefault = false 
const anyDefault = null
