// Code generated by sqlc. DO NOT EDIT.

package sqlcpg

import (
	"database/sql"
	"fmt"
	"time"

	"github.com/fahmifan/smol/internal/auth"
)

type Roles string

const (
	RolesAdmin Roles = "admin"
	RolesUser  Roles = "user"
	RolesGuest Roles = "guest"
)

func (e *Roles) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Roles(s)
	case string:
		*e = Roles(s)
	default:
		return fmt.Errorf("unsupported scan type for Roles: %T", src)
	}
	return nil
}

type Session struct {
	ID                    string
	UserID                string
	AccessToken           string
	AccessTokenExpiredAt  time.Time
	RefreshToken          string
	RefreshTokenExpiredAt time.Time
	CreatedAt             time.Time
}

type Todo struct {
	ID     string
	Detail string
	UserID string
	Done   bool
}

type User struct {
	ID    string
	Name  sql.NullString
	Email string
	Role  auth.Role
}
