// Code generated by sqlc. DO NOT EDIT.

package sqlcpg

import (
	"database/sql"
	"time"

	"github.com/fahmifan/smol/internal/rbac"
)

type Session struct {
	ID                    string
	UserID                string
	AccessToken           string
	AccessTokenExpiredAt  time.Time
	RefreshToken          string
	RefreshTokenExpiredAt time.Time
	CreatedAt             time.Time
}

type Todo struct {
	ID     string
	Detail string
	UserID string
	Done   bool
}

type User struct {
	ID    string
	Name  sql.NullString
	Email string
	Role  rbac.Role
}
