// Code generated by oto; DO NOT EDIT.

// HeadersFunc allows you to mutate headers for each request.
// Useful for adding authorization into the client.
interface HeadersFunc {
	(headers: Headers): void;
}

// Client provides access to remote services.
export class Client {
	// basepath is the path prefix for the requests.
	// This may be a path, or an absolute URL.
	public basepath: String = '/api/oto/'
	// headers allows calling code to mutate the HTTP
	// headers of the underlying HTTP requests.
	public headers?: HeadersFunc
}


export class SmolService {
	constructor(readonly client: Client) {}
	
		async addTodo(addTodoRequest?: AddTodoRequest, modifyHeaders?: HeadersFunc): Promise<Todo> {
		if (addTodoRequest == null) {
			addTodoRequest = new AddTodoRequest();
		}
		const headers: Headers = new Headers();
		headers.set('Accept', 'application/json');
		headers.set('Content-Type', 'application/json');
		if (this.client.headers) {
			await this.client.headers(headers);
		}
		if (modifyHeaders) {
			await modifyHeaders(headers)
		}
		const response = await fetch(this.client.basepath + 'SmolService.AddTodo', {
			method: 'POST',
			headers: headers,
			body: JSON.stringify(addTodoRequest),
		})
		if (response.status !== 200) {
			throw new Error(`SmolService.AddTodo: ${response.status} ${response.statusText}`);
		}
		return response.json().then((json) => {
			if (json.error) {
				throw new Error(json.error);
			}
			return new Todo(json);
		})
	}
	
		async findAllTodos(findAllTodosFilter?: FindAllTodosFilter, modifyHeaders?: HeadersFunc): Promise<Todos> {
		if (findAllTodosFilter == null) {
			findAllTodosFilter = new FindAllTodosFilter();
		}
		const headers: Headers = new Headers();
		headers.set('Accept', 'application/json');
		headers.set('Content-Type', 'application/json');
		if (this.client.headers) {
			await this.client.headers(headers);
		}
		if (modifyHeaders) {
			await modifyHeaders(headers)
		}
		const response = await fetch(this.client.basepath + 'SmolService.FindAllTodos', {
			method: 'POST',
			headers: headers,
			body: JSON.stringify(findAllTodosFilter),
		})
		if (response.status !== 200) {
			throw new Error(`SmolService.FindAllTodos: ${response.status} ${response.statusText}`);
		}
		return response.json().then((json) => {
			if (json.error) {
				throw new Error(json.error);
			}
			return new Todos(json);
		})
	}
	
		async findCurrentUser(empty?: Empty, modifyHeaders?: HeadersFunc): Promise<User> {
		if (empty == null) {
			empty = new Empty();
		}
		const headers: Headers = new Headers();
		headers.set('Accept', 'application/json');
		headers.set('Content-Type', 'application/json');
		if (this.client.headers) {
			await this.client.headers(headers);
		}
		if (modifyHeaders) {
			await modifyHeaders(headers)
		}
		const response = await fetch(this.client.basepath + 'SmolService.FindCurrentUser', {
			method: 'POST',
			headers: headers,
			body: JSON.stringify(empty),
		})
		if (response.status !== 200) {
			throw new Error(`SmolService.FindCurrentUser: ${response.status} ${response.statusText}`);
		}
		return response.json().then((json) => {
			if (json.error) {
				throw new Error(json.error);
			}
			return new User(json);
		})
	}
	
		async logoutUser(empty?: Empty, modifyHeaders?: HeadersFunc): Promise<Empty> {
		if (empty == null) {
			empty = new Empty();
		}
		const headers: Headers = new Headers();
		headers.set('Accept', 'application/json');
		headers.set('Content-Type', 'application/json');
		if (this.client.headers) {
			await this.client.headers(headers);
		}
		if (modifyHeaders) {
			await modifyHeaders(headers)
		}
		const response = await fetch(this.client.basepath + 'SmolService.LogoutUser', {
			method: 'POST',
			headers: headers,
			body: JSON.stringify(empty),
		})
		if (response.status !== 200) {
			throw new Error(`SmolService.LogoutUser: ${response.status} ${response.statusText}`);
		}
		return response.json().then((json) => {
			if (json.error) {
				throw new Error(json.error);
			}
			return new Empty(json);
		})
	}
	
}



export class AddTodoRequest {
	constructor(data?: any) {
		if (data) {
		
			
			this.detail = data.detail;
			
		
			
			this.done = data.done;
			
		
		}
	}

		detail: string = stringDefault;

		done: boolean = booleanDefault;

}

export class Empty {
	constructor(data?: any) {
		if (data) {
		
			
			this.error = data.error;
			
		
		}
	}

	// Error is string explaining what went wrong. Empty if everything was fine.
	error: string = stringDefault;

}

export class FindAllTodosFilter {
	constructor(data?: any) {
		if (data) {
		
			
			this.page = data.page;
			
		
			
			this.size = data.size;
			
		
		}
	}

		page: number = numberDefault;

		size: number = numberDefault;

}

export class Todo {
	constructor(data?: any) {
		if (data) {
		
			
			this.id = data.id;
			
		
			
			this.userID = data.userID;
			
		
			
			this.done = data.done;
			
		
			
			this.detail = data.detail;
			
		
			
			this.error = data.error;
			
		
		}
	}

		id: string = stringDefault;

		userID: string = stringDefault;

		done: boolean = booleanDefault;

		detail: string = stringDefault;

	// Error is string explaining what went wrong. Empty if everything was fine.
	error: string = stringDefault;

}

export class Todos {
	constructor(data?: any) {
		if (data) {
		
			
				
					if (data.todos) {
						this.todos = []
						for (let i = 0; i < data.todos.length; i++) {
							this.todos.push(new Todo(data.todos[i]));
						}
					}
				
			
		
			
			this.error = data.error;
			
		
		}
	}

		todos?: Todo[];

	// Error is string explaining what went wrong. Empty if everything was fine.
	error: string = stringDefault;

}

export class User {
	constructor(data?: any) {
		if (data) {
		
			
			this.id = data.id;
			
		
			
			this.email = data.email;
			
		
			
			this.role = data.role;
			
		
			
			this.error = data.error;
			
		
		}
	}

		id: string = stringDefault;

		email: string = stringDefault;

		role: string = stringDefault;

	// Error is string explaining what went wrong. Empty if everything was fine.
	error: string = stringDefault;

}


// these defaults make the template easier to write.
const stringDefault = ''
const numberDefault = 0
const booleanDefault = false 
const anyDefault = null
